#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv
from drenv import kubectl
from drenv import clusteradm

ADDONS = (
    "application-manager",
    "governance-policy-framework",
)

DEPLOYMENTS = {
    "open-cluster-management": (
        "governance-policy-addon-controller",
        "governance-policy-propagator",
        "multicluster-operators-appsub-summary",
        "multicluster-operators-channel",
        "multicluster-operators-placementrule",
        "multicluster-operators-subscription",
    ),
    "open-cluster-management-hub": (
        "cluster-manager-placement-controller",
        "cluster-manager-registration-controller",
        "cluster-manager-registration-webhook",
        "cluster-manager-work-webhook",
    ),
}


def deploy(cluster):
    drenv.log_progress("Initializing hub")
    clusteradm.init(wait=True, context=cluster)

    drenv.log_progress("Installing hub addons")
    clusteradm.install("hub-addon", names=ADDONS, context=cluster)


def wait(cluster):
    drenv.log_progress("Waiting until deployments are rolled out")
    for ns, names in DEPLOYMENTS.items():
        for name in names:
            deployment = f"deploy/{name}"
            drenv.wait_for(deployment, namespace=ns, profile=cluster)
            kubectl.rollout(
                "status",
                deployment,
                f"--namespace={ns}",
                "--timeout=300s",
                profile=cluster,
            )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
