kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics
  namespace: system
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics
