#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv
from drenv import kubectl


def deploy(cluster):
    drenv.log_progress("Creating rbd pool and storage class")
    kubectl.apply(
        "--filename",
        "rook-pool/replica-pool.yaml",
        "--filename",
        "rook-pool/storage-class.yaml",
        profile=cluster,
    )


def wait(cluster):
    drenv.log_progress("Waiting until ceph block pool is ready")
    drenv.wait_for(
        "cephblockpool/replicapool",
        output="jsonpath={.status.phase}",
        namespace="rook-ceph",
        timeout=60,
        profile=cluster,
    )
    kubectl.wait(
        "CephBlockPool",
        "replicapool",
        "--for",
        "jsonpath={.status.phase}=Ready",
        "--namespace",
        "rook-ceph",
        "--timeout",
        "300s",
        profile=cluster,
    )

    drenv.log_progress("Waiting for replica pool peer token")
    kubectl.wait(
        "CephBlockPool",
        "replicapool",
        "--for",
        "jsonpath={.status.info.rbdMirrorBootstrapPeerSecretName}=pool-peer-token-replicapool",
        "--namespace",
        "rook-ceph",
        "--timeout",
        "300s",
        profile=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
