#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("deploy", __file__)
test.add_argument(
    "--cluster",
    help="Cluster name to deploy on (default first cluster)",
)
args = test.parse_args()

cluster = args.cluster or test.env["clusters"][0]
test.info("Deploying on cluster '%s'", cluster)

test.deploy(cluster)
test.wait_for_drpc_status()
test.wait_until_drpc_is_stable()

test.info("Application was deployed successfully")
