#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("disable-dr", __file__)
args = test.parse_args()

test.info("Disable DR")
test.disable_dr()
test.info("DR was disabled")
