#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("enable-dr", __file__)
args = test.parse_args()

test.info("Enable DR")
test.enable_dr()
test.wait_for_drpc_status()
test.wait_until_drpc_is_stable()
test.info("DR enabled")
