#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("failover", __file__)
args = test.parse_args()

test.info("Fail over application")

test.wait_until_drpc_is_stable()
test.failover()
test.wait_until_drpc_is_stable()

test.info("Application was failed over")
