#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("relocate", __file__)
args = test.parse_args()

test.info("Relocate application")

test.wait_until_drpc_is_stable()
test.relocate()

# We must wait for the phase since both Available and PeerReady are true at
# this point. PeerReady becomes false when entering phase: Relocating
# progression: EnsuringVolumesAreSecondary.
test.wait_for_drpc_phase("Relocated")

test.wait_until_drpc_is_stable()

test.info("Application was relocated")
