#!/bin/bash -e

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

base="$(dirname $0)"

"$base/deploy" "$@"
"$base/protect" "$@"
"$base/failover" "$@"
"$base/relocate" "$@"
"$base/unprotect" "$@"
"$base/undeploy" "$@"
