#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("undeploy", __file__)
args = test.parse_args()

test.info("Deleting busybox example application")
test.undeploy()
test.info("Application was undeployed successfully")
