# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: dr1
spec:
  s3ProfileName: minio-on-dr1
  region: west
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: dr2
spec:
  s3ProfileName: minio-on-dr2
  region: east
