---
apiVersion: ramendr.openshift.io/v1alpha1
kind: Recipe
metadata:
  name: recipe-busybox
  namespace: recipe-test
spec:
  appType: busybox
  hooks:
  - name: service-hooks
    labelSelector:
      matchLabels:
        appname: busybox
    type: exec
    ops:
    - name: pre-backup
      container: busybox
      timeout: 10m
      # Command note: "/bin/sh -c" required when using non-executable files
      command:
      - "/bin/sh"
      - "-c"
      - "date"
    - name: pre-restore
      container: busybox
      timeout: 5m
      command:
      - "/bin/sh"
      - "-c"
      - "date"
  groups:
  - name: volumes
    type: volume
    labelSelector:
      matchLabels:
        appname: busybox
  - name: instance-resources
    backupRef: instance-resources
    type: resource
    includedResourceTypes:
    - deployment
    - pvc
  - name: deployments
    backupRef: instance-resources
    type: resource
    includedResourceTypes:
    - deployment
  - name: pvcs
    backupRef: instance-resources
    type: resource
    includedResourceTypes:
    - pvc
  captureWorkflow:
    sequence:
    - hook: service-hooks/pre-backup
    - group: instance-resources
  recoverWorkflow:
    sequence:
    - hook: service-hooks/pre-restore
    - group: pvcs
    - group: deployments
