---
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: bb
  namespace: recipe-test
spec:
  async:
    schedulingInterval: 1m
  pvcSelector:
    matchLabels:
      appname: busybox
  replicationState: primary
  s3Profiles:
  - minio-cluster1
  - minio-cluster2
  kubeObjectProtection:
    recipeRef:
      name: recipe-busybox
      captureWorkflowName: capture
      recoverWorkflowName: recover
      volumeGroupName: volumes
