#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import commands
from drenv import kubectl

NAMESPACE = "volsync-system"
DEPLOYMENT = "volsync"


def deploy(cluster):
    print("Adding helm backube repo")
    cmd = [
        "helm",
        "repo",
        "add",
        "backube",
        "https://backube.github.io/helm-charts/",
    ]
    for line in commands.watch(*cmd):
        print(line)

    print("Installing volsync")
    cmd = [
        "helm",
        "upgrade",
        "--install",
        "--create-namespace",
        "--namespace",
        NAMESPACE,
        DEPLOYMENT,
        "backube/volsync",
        "--kube-context",
        cluster,
    ]
    for line in commands.watch(*cmd):
        print(line)


def wait(cluster):
    print(f"Waiting until deployment {DEPLOYMENT} is rolled out")
    kubectl.rollout(
        "status",
        f"deploy/{DEPLOYMENT}",
        f"--namespace={NAMESPACE}",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
