# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2e"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/test/timestamp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ramendev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
