---
# yamllint disable rule:line-length
# Ref template: https://github.com/golangci/golangci-lint/blob/v1.37.1/.golangci.example.yml

# options for analysis running
run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  exhaustive:
    # check switch statements in generated files also
    check-generated: true
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  goheader:
    template: |
      SPDX-FileCopyrightText: The RamenDR authors
      SPDX-License-Identifier: Apache-2.0
  misspell:
    locale: US
  wsl:
    allow-trailing-comment: true
    enforce-err-cuddling: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - paralleltest
    - goerr113  # TODO: Need to introduce error definition and bring this back
    - goheader  # TODO: Introduce back post fixing linter errors
    - gci
    - interfacer  # interfacer linter is archived and deprecated (https://github.com/mvdan/interfacer)
    # TODO: fix folloing linter errors.
    - exhaustruct
    - tagliatelle
    - gomoddirectives
    - goimports
    - wrapcheck
    - varnamelen
    - staticcheck
    - nosnakecase
    - ireturn
    - nilnil
    - containedctx
    - nonamedreturns
    - forcetypeassert
    - promlinter
    - contextcheck
    - errname
