#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

FILE_SYSTEMS = ["test-fs1", "test-fs2"]


def deploy(cluster):
    for file_system in FILE_SYSTEMS:
        print("Creating CephFS instance")
        template = drenv.template("filesystem.yaml")
        yaml = template.substitute(cluster=cluster, name=file_system)
        kubectl.apply("--filename=-", input=yaml, context=cluster)

        print("Creating StorageClass")
        template = drenv.template("storage-class.yaml")
        yaml = template.substitute(cluster=cluster, fsname=file_system)
        kubectl.apply("--filename=-", input=yaml, context=cluster)

    print("Creating SnapshotClass")
    template = drenv.template("snapshot-class.yaml")
    yaml = template.substitute(cluster=cluster)
    kubectl.apply("--filename=-", input=yaml, context=cluster)


def wait(cluster):
    print("Waiting until Ceph File Systems are ready")

    for file_system in FILE_SYSTEMS:
        drenv.wait_for(
            f"cephfilesystem/{file_system}",
            output="jsonpath={.status.phase}",
            namespace="rook-ceph",
            timeout=120,
            profile=cluster,
        )
        kubectl.wait(
            f"cephfilesystem/{file_system}",
            "--for=jsonpath={.status.phase}=Ready",
            "--namespace=rook-ceph",
            "--timeout=300s",
            context=cluster,
        )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
