#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import cache
from drenv import kubectl


def deploy(cluster):
    print("Creating CephFS instance and storage/snapshot classes")
    path = cache.get(".", "addons/rook-cephfs-1.14.yaml")
    kubectl.apply("--filename", path, context=cluster)


def wait(cluster):
    print("Waiting until CephFS is ready")
    drenv.wait_for(
        "cephfilesystem/myfs",
        output="jsonpath={.status.phase}",
        namespace="rook-ceph",
        timeout=120,
        profile=cluster,
    )
    kubectl.wait(
        "cephfilesystem/myfs",
        "--for=jsonpath={.status.phase}=Ready",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
