#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import kubectl

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

print("Deploying example")
kubectl.apply("--filename", "deployment.yaml", context=cluster)

print("Waiting until example deployment is rolled out")
kubectl.rollout(
    "status",
    "deploy/example-deployment",
    timeout=180,
    context=cluster,
)

print("waiting until pod is ready")
kubectl.wait(
    "pod",
    "--selector=app=example",
    "--for=condition=Ready",
    timeout=180,
    context=cluster,
)
