#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import kubectl

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

print("Testing example deployment")
hostname = kubectl.exec(
    "deploy/example-deployment", "--", "hostname", context=cluster
).rstrip()
if not hostname.startswith("example-deployment-"):
    raise RuntimeError(f"Unexpected hostname: '{hostname}'")
