#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

# Using main since there are no releases, last tag is more than year old and
# the image contains 36 vulnerabilities.
VERSION = "main"

BASE_URL = f"https://raw.githubusercontent.com/stolostron/multicloud-operators-foundation/{VERSION}/deploy/foundation/hub"


def deploy(cluster):
    print("Deploying ocm controller")
    with drenv.kustomization(
        "kustomization.yaml",
        base_url=BASE_URL,
    ) as kustomization:
        kubectl.apply("--kustomize", kustomization, context=cluster)


def wait(cluster):
    print("Waiting for ocm controller rollout")
    kubectl.rollout(
        "status",
        "deploy/ocm-controller",
        "--namespace=open-cluster-management",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
