#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv.addons.rook import external_cluster

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} cluster external_storage_cluster")
    sys.exit(1)

cluster = sys.argv[1]
external_storage_cluster = sys.argv[2]

external_cluster.start(cluster, external_storage_cluster)
