#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import yaml

from drenv import kubectl

os.chdir(os.path.dirname(__file__))

with open("config.yaml") as f:
    config = yaml.safe_load(f)

parser = argparse.ArgumentParser("undeploy")
parser.add_argument("env_type", choices=config["env_types"])
args = parser.parse_args()

print(f"Unconfiguring Ramen for {args.env_type}")


print("Deleting samples channel")
kubectl.delete(
    "--filename",
    "samples-channel.yaml",
    "--ignore-not-found",
    context=config["hub"],
)

print("Deleting DRClusters and DRPolicy")
kubectl.delete(
    "--kustomize",
    args.env_type,
    "--ignore-not-found",
    context=config["hub"],
)

# We keep the ramen config map since we do not own it.

print("Deleting s3 secret in ramen hub namespace")
kubectl.delete(
    "--filename",
    "s3-secret.yaml",
    "--ignore-not-found",
    context=config["hub"],
)

print("Ramen was unconfigured successfully")
