#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv.addons import error

duration = float(sys.argv[1])

error.start(duration)
