#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv

# Update this when upgrading rook.
VERSION = "release-1.10"
BASE_URL = f"https://raw.githubusercontent.com/rook/rook/{VERSION}/deploy/examples"


def deploy(cluster):
    drenv.log_progress("Deploying rook ceph cluster")
    with drenv.kustomization(
        "rook-cluster/kustomization.yaml",
        base_url=BASE_URL,
    ) as kustomization:
        drenv.kubectl("apply", "--kustomize", kustomization, profile=cluster)


def wait(cluster):
    drenv.log_progress("Waiting until rook ceph cluster is ready")
    drenv.wait_for(
        "cephcluster/my-cluster",
        output="jsonpath={.status.phase}",
        namespace="rook-ceph",
        timeout=60,
        profile=cluster,
    )
    drenv.kubectl(
        "wait",
        "CephCluster",
        "my-cluster",
        "--for",
        "jsonpath={.status.phase}=Ready",
        "--namespace",
        "rook-ceph",
        "--timeout",
        "300s",
        profile=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
