#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import json
import os
import sys

import yaml

import drenv
from drenv import kubectl


def deploy(cluster):
    print("Creating RBD pool and storage/snapshot classes")

    template = drenv.template("storage-class.yaml")
    yaml = template.substitute(cluster=cluster)

    kubectl.apply("--filename=-", input=yaml, context=cluster)
    kubectl.apply(
        "--filename=replica-pool.yaml",
        "--filename=snapshot-class.yaml",
        context=cluster,
    )


def wait(cluster):
    print("Waiting until ceph block pool is ready")
    drenv.wait_for(
        "cephblockpool/replicapool",
        output="jsonpath={.status.phase}",
        namespace="rook-ceph",
        timeout=120,
        profile=cluster,
    )
    kubectl.wait(
        "cephblockpool/replicapool",
        "--for=jsonpath={.status.phase}=Ready",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=cluster,
    )

    print("Waiting for replica pool peer token")
    kubectl.wait(
        "cephblockpool/replicapool",
        "--for=jsonpath={.status.info.rbdMirrorBootstrapPeerSecretName}=pool-peer-token-replicapool",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=cluster,
    )

    out = kubectl.get(
        "cephblockpool/replicapool",
        "--output=jsonpath={.status}",
        "--namespace=rook-ceph",
        context=cluster,
    )
    info = {"ceph pool status": json.loads(out)}
    print(yaml.dump(info, sort_keys=False))


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
