apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: alerting-rules
  namespace: system
spec:
  groups:
    - name: recording_rules
      rules:
        - record: ramen_sync_duration_seconds
          expr: (time() - (ramen_last_sync_timestamp_seconds{job='ramen-hub-operator-metrics-service'} > 0))
        - record: ramen_rpo_difference
          expr: ramen_sync_duration_seconds / on(policyname) group_left() (ramen_policy_schedule_interval_seconds{job="ramen-hub-operator-metrics-service"})
    - name: alerts
      rules:
        - alert: VolumeSynchronizationDelay
          expr: ramen_rpo_difference >= 3
          for: 5s
          labels:
            severity: critical
          annotations:
            description: "Syncing of volumes (DRPC: {{ $labels.obj_name }}, Namespace: {{ $labels.obj_namespace }}) is taking more than thrice the scheduled snapshot interval. This may cause data loss and a backlog of replication requests."
            alert_type: "DisasterRecovery"
        - alert: VolumeSynchronizationDelay
          expr: ramen_rpo_difference > 2 and ramen_rpo_difference < 3
          for: 5s
          labels:
            severity: warning
          annotations:
            description: "Syncing of volumes (DRPC: {{ $labels.obj_name }}, Namespace: {{ $labels.obj_namespace }}) is taking more than twice the scheduled snapshot interval. This may cause data loss and impact replication requests."
            alert_type: "DisasterRecovery"
    