#!/usr/bin/env -S python3 -u

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

drenv.log_progress("Deploying minio")
drenv.kubectl("apply", "--filename", "minio/minio.yaml", profile=cluster)

drenv.log_progress("Waiting until minio is rolled out")
drenv.kubectl(
    "rollout", "status", "deployment/minio",
    "--namespace", "minio",
    "--timeout", "180s",
    profile=cluster,
)
