#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv import kubectl


def deploy(cluster):
    print("Deploying minio")
    kubectl.apply("--filename", "minio/minio.yaml", profile=cluster)


def wait(cluster):
    print("Waiting until minio is rolled out")
    kubectl.rollout(
        "status",
        "deployment/minio",
        "--namespace=minio",
        "--timeout=300s",
        profile=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
