// SPDX-FileCopyrightText: The RamenDR authors
// SPDX-License-Identifier: Apache-2.0

package util

import (
	"fmt"
	"sync"
	"time"

	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/record"
)

// This implementation of events infrastructure is mainly based on
// the way events is handled in the ocs-operator.
// https://github.com/openshift/ocs-operator/blob/master/controllers/util/events.go
const (
	LastEventValidDuration = 10
)

const (
	// NonConsistencyGroupDeprecatedEventInterval is the minimum time between
	// repeated deprecation warnings for one object. The first warning is
	// emitted when non-consistency-group VolumeReplication is first observed.
	NonConsistencyGroupDeprecatedEventInterval = 6 * time.Hour

	// NonConsistencyGroupDeprecatedMessage is the stable warning text. It must
	// not include values that change between reconciles, so event aggregation
	// and filtering stay reliable.
	NonConsistencyGroupDeprecatedMessage = "Warning DeprecatedFeature: " +
		"VolumeReplication without consistency groups is deprecated and will be removed in a future release. " +
		"Use consistency groups for new and existing workloads."
)

const (
	// Events generated by VolumeReplicationGroup reconciler

	// EventReasonValidationFailed is used when VolumeReplicationGroup validation fails
	EventReasonValidationFailed = "FailedValidation"

	// EventReasonPVCListFailed is used when VRG fails to get the list of PVCs
	EventReasonPVCListFailed = "PVCListFailed"

	// EventReasonVRCreateFailed is used when VRG fails to create VolRep resource
	EventReasonVRCreateFailed = "VRCreateFailed"

	// EventReasonVRCreateFailed is used when VRG fails to update VolRep resource
	EventReasonVRUpdateFailed = "VRUpdateFailed"

	// EventReasonProtectPVCFailed is used when VRG fails to protect PVC
	EventReasonProtectPVCFailed = "ProtectPVCFailed"

	// EventReasonUploadFailed is used when VRG fails to upload PV cluster data
	EventReasonUploadFailed = "UploadFailed"

	// EventReasonVrgUploadFailed is used when VRG fails to upload VRG object
	EventReasonVrgUploadFailed = "VrgUploadFailed"

	// EventReasonPrimarySuccess is an event generated when VRG is successfully
	// processed as Primary.
	EventReasonPrimarySuccess = "PrimaryVRGProcessSuccess"

	// EventReasonSecondarySuccess is an event generated when VRG is successfully
	// processed as Primary.
	EventReasonSecondarySuccess = "SecondaryVRGProcessSuccess"

	// EventReasonSecondarySuccess is an event generated when VRG is successfully
	// processed as Primary.
	EventReasonDeleteSuccess = "VRGDeleteSuccess"
	// TODO: Add any additional events (or remove one of existing ones above) if necessary.

	// Events for DRPC Reconciler

	// EventReasonDeploying is generated when DRPC begins to deploy ramen manged cluster
	// component(s) and the application
	EventReasonDeploying = "DRPCDeploying"

	// EventReasonDeployFail is an event generated when DRPC fails to do
	// a successful initial deployment of the application and ramen managed
	// cluster component(s)
	EventReasonDeployFail = "DRPCDeployFailed"

	// EventReasonDeploySuccess is an event generated when DRPC successfully
	// deploys ramen and the application in the managed cluster initially
	EventReasonDeploySuccess = "DRPCDeploySuccess"

	// EventReasonFailingOver is an event generated when DRPC starts the failover
	// process
	EventReasonFailingOver = "DRPCFailingOver"

	// EventReasonFailoverSuccess is an evenet generated when DRPC does a successful
	// failover
	EventReasonFailoverSuccess = "DRPCFailoverSuccess"

	// EventReasonRelocating is an event generated when DRPC starts relocating
	EventReasonRelocating = "DRPCRelocating"

	// EventReasonRelocationSuccess is an event generated when DRPC successfully
	// relocates an application along with ramen managed cluster component(s)
	EventReasonRelocationSuccess = "DRPCRelocationSuccess"

	// EventReasonSwitchFailed is generated when DRPC fails to switch the cluster
	// where the app is placed
	EventReasonSwitchFailed = "DRPCClusterSwitchFailed"

	// EventReasonNonConsistencyGroupDeprecated is emitted while VolumeReplication
	// is used without consistency groups. The reason is stable so users can
	// filter on it and Kubernetes can aggregate the warning.
	EventReasonNonConsistencyGroupDeprecated = "NonConsistencyGroupDeprecated"
)

// EventReporter is custom events reporter type which allows user to limit the events
type EventReporter struct {
	recorder record.EventRecorder

	// lastReportedEvent will have a last captured event
	lastReportedEvent map[string]string

	// lastReportedEventTime will be the time of lastReportedEvent
	lastReportedEventTime map[string]time.Time

	// lastIntervalEventTime tracks warnings that are emitted on a transition
	// and then at most once per interval. It is separate from lastReportedEvent
	// so a deprecation warning cannot replace or be replaced by another event
	// for the same object.
	lastIntervalEventTime map[string]time.Time

	// Mutex for protecting concurrent access to the recorder map
	mutex sync.Mutex
}

// NewEventReporter returns EventReporter object
func NewEventReporter(recorder record.EventRecorder) *EventReporter {
	return &EventReporter{
		recorder:              recorder,
		lastReportedEvent:     make(map[string]string),
		lastReportedEventTime: make(map[string]time.Time),
		lastIntervalEventTime: make(map[string]time.Time),
	}
}

// ReportIfNotPresent will report event if lastReportedEvent is not the same in last 10 minutes
// TODO: The duration 10 minutes can be changed to some other value if necessary
func ReportIfNotPresent(recorder *EventReporter, instance runtime.Object,
	eventType, eventReason, msg string,
) {
	nameSpacedName, err := getNameSpacedName(instance)
	if err != nil {
		return
	}

	eventKey := getEventKey(eventType, eventReason, msg)

	recorder.mutex.Lock()
	defer recorder.mutex.Unlock()

	if recorder.lastReportedEvent[nameSpacedName] != eventKey ||
		recorder.lastReportedEventTime[nameSpacedName].Add(time.Second*LastEventValidDuration).Before(time.Now()) {
		recorder.lastReportedEvent[nameSpacedName] = eventKey
		recorder.lastReportedEventTime[nameSpacedName] = time.Now()
		recorder.recorder.Event(instance, eventType, eventReason, msg)
	}
}

func getNameSpacedName(instance runtime.Object) (string, error) {
	objMeta, err := meta.Accessor(instance)
	if err != nil {
		return "", fmt.Errorf("failed to access the instance from object")
	}

	return objMeta.GetNamespace() + ":" + objMeta.GetName(), nil
}

func getEventKey(eventType, eventReason, msg string) string {
	return fmt.Sprintf("%s:%s:%s", eventType, eventReason, msg)
}

// ReportAtInterval emits an event the first time it is requested for an object
// and reason, then suppresses further events until interval has elapsed.
// now is supplied by the caller so tests can control the clock. A nil recorder
// does not emit.
func ReportAtInterval(recorder *EventReporter, instance runtime.Object, eventType, eventReason, msg string,
	interval time.Duration, now time.Time,
) bool {
	if recorder == nil || recorder.recorder == nil {
		return false
	}

	key, err := intervalEventKey(instance, eventReason)
	if err != nil {
		return false
	}

	recorder.mutex.Lock()
	defer recorder.mutex.Unlock()

	if recorder.lastIntervalEventTime == nil {
		recorder.lastIntervalEventTime = make(map[string]time.Time)
	}

	if last, ok := recorder.lastIntervalEventTime[key]; ok && now.Sub(last) < interval {
		return false
	}

	recorder.lastIntervalEventTime[key] = now
	recorder.recorder.Event(instance, eventType, eventReason, msg)

	return true
}

// ForgetInterval drops the rate-limit entry for an object and reason so the
// next applicable observation emits immediately.
func ForgetInterval(recorder *EventReporter, instance runtime.Object, eventReason string) {
	if recorder == nil {
		return
	}

	key, err := intervalEventKey(instance, eventReason)
	if err != nil {
		return
	}

	recorder.mutex.Lock()
	defer recorder.mutex.Unlock()

	delete(recorder.lastIntervalEventTime, key)
}

func intervalEventKey(instance runtime.Object, eventReason string) (string, error) {
	objMeta, err := meta.Accessor(instance)
	if err != nil {
		return "", fmt.Errorf("failed to access the instance from object")
	}

	return string(objMeta.GetUID()) + ":" + objMeta.GetNamespace() + ":" +
		objMeta.GetName() + ":" + eventReason, nil
}
