# permissions for end users to view appvolumereplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appvolumereplication-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - appvolumereplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - appvolumereplications/status
  verbs:
  - get
