# permissions for end users to edit appvolumereplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appvolumereplication-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - appvolumereplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - appvolumereplications/status
  verbs:
  - get
