apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 9289
    targetPort: 9289
  selector:
    control-plane: controller-manager
