# permissions for end users to view drclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drcluster-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusters/status
  verbs:
  - get
