# permissions for end users to edit maintenancemodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maintenancemode-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - maintenancemodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - maintenancemodes/status
  verbs:
  - get
