kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics
  namespace: system
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
