# permissions for end users to view protectedvolumereplicationgrouplists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: protectedvolumereplicationgrouplist-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - protectedvolumereplicationgrouplists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - protectedvolumereplicationgrouplists/status
  verbs:
  - get
