# permissions for end users to edit protectedvolumereplicationgrouplists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: protectedvolumereplicationgrouplist-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - protectedvolumereplicationgrouplists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - protectedvolumereplicationgrouplists/status
  verbs:
  - get
