# permissions for end users to view replicationgroupdestinations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicationgroupdestination-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ramen
    app.kubernetes.io/part-of: ramen
    app.kubernetes.io/managed-by: kustomize
  name: replicationgroupdestination-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - replicationgroupdestinations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - replicationgroupdestinations/status
  verbs:
  - get
