#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import json
import os
import sys

import drenv
from drenv import cluster
from drenv import clusteradm
from drenv import kubectl

ADDONS = (
    {
        "name": "application-manager",
        "deployment": "application-manager",
    },
    {
        "name": "governance-policy-framework",
        "deployment": "governance-policy-framework",
    },
    {
        "name": "config-policy-controller",
        "deployment": "config-policy-controller",
    },
)

ADDONS_NAMESPACE = "open-cluster-management-agent-addon"
HUB_NAMESPACE = "open-cluster-management-hub"

# These are deployed when running "clusteradm init" on the hub.
# We wait for them before we try to join the hub.
HUB_DEPLOYMENTS = (
    "cluster-manager-placement-controller",
    "cluster-manager-registration-controller",
    "cluster-manager-registration-webhook",
    "cluster-manager-work-webhook",
)


def deploy(cluster, hub):
    wait_for_hub(hub)
    join_cluster(cluster, hub)
    label_cluster(cluster, hub)
    wait_for_managed_cluster(cluster, hub)
    enable_addons(cluster, hub)


def wait(cluster):
    print("Waiting until deployments are rolled out")
    for addon in ADDONS:
        deployment = f"deploy/{addon['deployment']}"
        drenv.wait_for(deployment, namespace=ADDONS_NAMESPACE, profile=cluster)
        kubectl.rollout(
            "status",
            deployment,
            f"--namespace={ADDONS_NAMESPACE}",
            "--timeout=300s",
            context=cluster,
        )


def wait_for_hub(hub):
    print(f"Waiting until cluster '{hub}' is ready")

    cluster.wait_until_ready(hub)
    drenv.wait_for(f"namespace/{HUB_NAMESPACE}", profile=hub)

    for name in HUB_DEPLOYMENTS:
        deployment = f"deploy/{name}"
        drenv.wait_for(deployment, namespace=HUB_NAMESPACE, profile=hub)
        kubectl.rollout(
            "status",
            deployment,
            f"--namespace={HUB_NAMESPACE}",
            "--timeout=300s",
            context=hub,
        )


def join_cluster(cluster, hub):
    print(f"Joining cluster '{hub}'")

    out = clusteradm.get("token", output="json", context=hub)
    hub_info = json.loads(out)

    clusteradm.join(
        hub_token=hub_info["hub-token"],
        hub_apiserver=hub_info["hub-apiserver"],
        cluster_name=cluster,
        wait=True,
        context=cluster,
    )


def label_cluster(cluster, hub):
    # Managed cluster must have name=cluster label in addition to
    # metadata.name.
    # https://github.com/open-cluster-management-io/multicloud-operators-subscription/issues/16
    print("Labelling cluster")
    kubectl.label(
        f"managedclusters/{cluster}",
        f"name={cluster}",
        overwrite=True,
        context=hub,
    )


def wait_for_managed_cluster(cluster, hub):
    print("Waiting until managed cluster is available")
    kubectl.wait(
        f"managedcluster/{cluster}",
        "--for=condition=ManagedClusterConditionAvailable",
        "--timeout=60s",
        context=hub,
    )


def enable_addons(cluster, hub):
    print("Enabling addons")
    names = [addon["name"] for addon in ADDONS]
    clusteradm.addon("enable", names=names, clusters=[cluster], context=hub)


if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} cluster hub")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster_name = sys.argv[1]
hub_name = sys.argv[2]

deploy(cluster_name, hub_name)
wait(cluster_name)
