apiVersion: ramendr.openshift.io/v1alpha1
kind: RamenConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:9289
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: dr-cluster.ramendr.openshift.io
ramenControllerType: "dr-cluster"
