---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ramen-dr-cluster-operator-config
  namespace: ramen-system
data:
  ramen_manager_config.yaml: |
    s3StoreProfiles:
    - s3ProfileName: minio-cluster1
      s3Bucket: velero
      s3CompatibleEndpoint: http://minikube-ip-cluster1:30000
      s3Region: us-east-1
      s3SecretRef:
        name: minio-s3
        namespace: ramen-system
      VeleroNamespaceSecretKeyRef:
        key: cloud
        name: cloud-credentials
    - s3ProfileName: minio-cluster2
      s3Bucket: velero
      s3CompatibleEndpoint: http://minikube-ip-cluster2:30000
      s3Region: us-east-1
      s3SecretRef:
        name: minio-s3
        namespace: ramen-system
      VeleroNamespaceSecretKeyRef:
        key: cloud
        name: cloud-credentials
    drClusterOperator:
      deploymentAutomationEnabled: true
      s3SecretDistributionEnabled: true
      channelName: alpha
      packageName: ramen-dr-cluster-operator
      namespaceName: ramen-system
      catalogSourceName: ramen-catalog
      catalogSourceNamespaceName: ramen-system
      clusterServiceVersionName: ramen-dr-cluster-operator.v0.0.1
    veleroNamespaceName: "velero"
