# Copy of:
#  github.com/rook/rook/blob/release-1.8/deploy/examples/cluster-test.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false
    bdev_flock_retry = 20
    bluefs_buffered_io = false
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  # On Minikube /var/lib/rook is not persisted, but anything under /data is.
  # https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/#a-note-on-mounts-persistence-and-minikube-hosts
  dataDirHostPath: /data/rook
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.6
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  disruptionManagement:
    managePodBudgets: true
  network:
    provider: host
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: device-health-metrics
  namespace: rook-ceph
spec:
  name: device_health_metrics
  failureDomain: host
  replicated:
    size: 1
    requireSafeReplicaSize: false
