apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-fs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-fs