#!/bin/bash -e

venv=~/.venv/ramen

if [ -d "$venv" ]; then
    echo "Virtual environemnt exists: '$venv'"
else
    echo "Creating virtual environment: '$venv'"
    python3 -m venv $venv
fi

echo "Upgrading pip..."
$venv/bin/pip install --upgrade pip

echo "Installing drenv..."
$venv/bin/pip install -e test

echo "Installing ramenctl..."
$venv/bin/pip install -e ./ramenctl

echo "Installing development tools"
$venv/bin/pip install -r requirements.txt

echo "Enabling full test coverage"
cp coverage.pth $venv/lib/python*/site-packages

echo "Adding venv symlink..."
ln -sf $venv/bin/activate venv

echo
echo "To activate the environment run:"
echo
echo "    source venv"
echo
