---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  config/**
  config-dro/**
  config-drm/**
  hack/test/*
rules:
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
