#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os

from drenv import cache

os.chdir(os.path.dirname(__file__))
path = cache.path("addons/rook-cluster-1.14.yaml")
cache.fetch(".", path)
