#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

# Update this when upgrading rook.
VERSION = "release-1.13"
BASE_URL = f"https://raw.githubusercontent.com/rook/rook/{VERSION}/deploy/examples"


def deploy(cluster):
    print("Deploying rook ceph cluster")
    with drenv.kustomization(
        "kustomization.yaml",
        base_url=BASE_URL,
    ) as kustomization:
        kubectl.apply("--kustomize", kustomization, context=cluster)


def wait(cluster):
    print("Waiting until rook ceph cluster is ready")
    drenv.wait_for(
        "cephcluster/my-cluster",
        output="jsonpath={.status.phase}",
        namespace="rook-ceph",
        profile=cluster,
    )
    kubectl.wait(
        "cephcluster/my-cluster",
        "--for=jsonpath={.status.phase}=Ready",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
