apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ramen.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ApplicationVolumeReplication is the Schema for the applicationvolumereplications
        API
      displayName: Application Volume Replication
      kind: ApplicationVolumeReplication
      name: applicationvolumereplications.ramendr.openshift.io
      version: v1alpha1
    - description: ClusterPeers is the Schema for the clusterpeers API
      displayName: Cluster Peers
      kind: ClusterPeers
      name: clusterpeers.ramendr.openshift.io
      version: v1alpha1
    - description: VolumeReplicationGroup is the Schema for the volumereplicationgroups
        API
      displayName: Volume Replication Group
      kind: VolumeReplicationGroup
      name: volumereplicationgroups.ramendr.openshift.io
      version: v1alpha1
  description: Ramen is a disaster-recovery orchestrator for stateful applications
    across a set of peer kubernetes clusters which are deployed and managed using
    open-cluster-management (OCM) and provides cloud-native interfaces to orchestrate
    the life-cycle of an application's state on PersistentVolumes.
  displayName: RamenDR
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Storage
  - Integration & Delivery
  - OpenShift Optional
  links:
  - name: Ramen
    url: https://ramen.domain
  maintainers:
  - email: bmekhiss@redhat.com
    name: Benamar Mekhissi
  - email: srangana@redhat.com
    name: Shyam Ranganathan
  - email: vdeenadh@redhat.com
    name: Veera Deenadhayalan
  maturity: alpha
  provider:
    name: ramen-operator
    url: https://github.com/RamenDR/ramen
  version: 0.0.0
