#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv.addons import recipe

if len(sys.argv) != 2:
    sys.exit(f"Usage: {sys.argv[0]} cluster")

cluster = sys.argv[1]

recipe.start(cluster)
