---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1
  labels:
    appclass: gold
    environment: dev.AZ1
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
