---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: busybox
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          emit() {
              echo "$(date) $1" | tee -a /var/log/ramen.log
              sync
          }
          trap "emit STOP; exit" TERM
          emit START
          while true; do
              sleep 10 & wait
              emit UPDATE
          done
        image: quay.io/nirsof/busybox:stable
        imagePullPolicy: IfNotPresent
        name: logger
        volumeMounts:
        - mountPath: /var/log
          name: varlog
      volumes:
      - name: varlog
        persistentVolumeClaim:
          claimName: busybox-pvc
