#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
from drenv import cache

os.chdir(os.path.dirname(__file__))
cache.refresh("crds", "addons/odf-external-snapshotter-crds-8.2.yaml")
cache.refresh("controller", "addons/odf-external-snapshotter-controller-8.2.yaml")
