#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import kubectl
from drenv import cache


def deploy(cluster):
    print("Deploying crds")
    path = cache.get("crds", "addons/odf-external-snapshotter-8.2.yaml")
    kubectl.apply("--filename", path, context=cluster)

    print("Waiting until crds are established")
    kubectl.wait("--for=condition=established", "--filename", path, context=cluster)


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
