apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: drpolicy-sample
spec:
  schedulingInterval: "1h"  # hourly
  replicationClassSelector:
    matchLabels:
      class: ramen
  drClusterSet:
    - name: east
      s3ProfileName: s3-profile-of-east
    - name: west
      s3ProfileName: s3-profile-of-west
