apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  replicationState: "Primary"
  s3Profiles:
    - minio-on-eyewall4
    - minio-on-cluster1
  async:
    mode: Enabled
    schedulingInterval: "10m"
  sync:
    mode: Disabled
  replicationState: "primary"
