apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: drpolicy-sample
spec:
  schedulingInterval: "1h"  # hourly
  replicationClassSelector:
    matchLabels:
      class: ramen-replication-class
  volumeSnapshotClassSelector:
    matchLabels:
      class: ramen-snapshot-class
  drClusters:
    - east
    - west
