apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  schedulingInterval: "1h"
  replicationState: "Primary"
  replicationSelector:
    matchLabels:
      class: ramen
  s3ProfileNames:
    - s3-profile-of-east
    - s3-profile-of-west
