apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drplacementcontrol-sample
  namespace: application-namespace
spec:
  preferredCluster: "east"
  drPolicyRef:
    name: drpolicy-sample
  placementRef:
    kind: PlacementRule
    name: application-placement-rule
  pvcSelector:
    matchLabels:
      any-pvc-label: value
