apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  volumeReplicationClass: "storage-replication-class"
  replicationState: "Primary"
  s3Endpoint: "path/to/s3Endpoint"
  s3Region: "unknown"
  s3SecretName: secret-name-with-s3-credentials
