apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drplacementcontrol-sample
  namespace: application-namespace
spec:
  preferredCluster: "east"
  drPolicyRef:
    name: drpolicy-sample
  placementRef:
    kind: PlacementRule
    name: application-placement-rule
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  kubeObjectProtection:
    captureInterval: 1m
    captureOrder:
      - name: config
        includedResources: ["ConfigMap", "Secret"]
      - name: everything
        includeClusterResources: true
        excludedResources: ["ConfigMap", "Secret"]
    recoverOrder:
      - backupName: config
        includedResources: ["ConfigMap", "Secret"]
      - backupName: everything
        includedResources: ["*"]
