apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  replicationState: "Primary"
  s3Profiles:
    - s3-profile-of-east
    - s3-profile-of-west
  async:
    mode: Enabled
    schedulingInterval: "10m"
  sync:
    mode: Disabled
  replicationState: "primary"
  kubeObjectProtection:
    resourceCaptureOrder:
      - ["Deployments"]
      - ["*.cpd.ibm.com"]
      - ["ConfigMap", "Secret"]
      - [".*"]
    resourceRecoveryOrder:
      - ["Secret",
        "ConfigMap"]
      - ["*.cpd.ibm.com"]
      - ["!Deployments"]
      - [".*"]
