apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample-1
spec:
  # Add fields here
  pvcSelector:
    matchLabels:
      appclass: gold
      environment: dev.AZ1
  volumeReplicationClass: "WAN-DR-Low-RPO-Apps"
  replicationState: "Primary"
