apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  replicationState: "Primary"
  s3ProfileNames:
    - s3-profile-of-east
    - s3-profile-of-west
  async:
    mode: Enabled
    schedulingInterval: "10m"
    replicationSelector:
      matchLabels:
        class: ramen
