apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drplacementcontrol-sample
  namespace: application-namespace
spec:
  preferredCluster: "east"
  drPolicyRef:
    name: drpolicy-sample
  placementRef:
    kind: PlacementRule
    name: application-placement-rule
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  s3Endpoint: "path/to/s3Endpoint"
  s3Region: "unknown"
  s3SecretName: secret-name-with-s3-credentials
