apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample
spec:
  pvcSelector:
    matchLabels:
      any-pvc-label: value
  volumeReplicationClass: "storage-replication-class"
  replicationState: "primary"
  s3ProfileName: "Noobaa-on-Peer-Cluster"
