apiVersion: ramendr.openshift.io/v1alpha1
kind: AppVolumeReplication
metadata:
  name: appvolumereplication-sample
  namespace: default
spec:
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
  failedCluster: empty
