#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

VERSION = "v0.7.0"
BASE_URL = f"https://raw.githubusercontent.com/csi-addons/kubernetes-csi-addons/{VERSION}/deploy/controller"


def deploy(cluster):
    print("Deploying csi addon for volume replication")
    with drenv.kustomization(
        "kustomization.yaml",
        base_url=BASE_URL,
        image_tag=VERSION,
    ) as kustomization:
        kubectl.apply("--kustomize", kustomization, context=cluster)


def wait(cluster):
    print("Waiting until csi-addons-controller-manager is rolled out")
    kubectl.rollout(
        "status",
        "deploy/csi-addons-controller-manager",
        "--namespace=csi-addons-system",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
