#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} cluster1 cluster2")
    sys.exit(1)

clusters = sys.argv[1:]

for cluster in clusters:
    drenv.log_progress(f"Testing example deployment on cluster {cluster}")
    drenv.kubectl(
        "rollout", "status", "deploy/example-deployment",
        "--timeout", "60s",
        profile=cluster,
    )
