#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv
from drenv import kubectl

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

drenv.log_progress("Testing example deployment")
kubectl.rollout(
    "status",
    "deploy/example-deployment",
    "--timeout=180s",
    profile=cluster,
)
