#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import time
from drenv import test

test.start("test", __file__)
test.add_argument(
    "--delay",
    type=int,
    default=0,
    help="delay before deleting application",
)
args = test.parse_args()

test.info("Fail over application")
test.wait_until_drpc_is_stable()
test.failover()
test.wait_for_drpc_progression("Cleaning Up")

if args.delay:
    test.info("Deleting application in %s seconds...", args.delay)
    time.sleep(args.delay)

test.info("Deleting application")
test.delete_application()

test.info("Inspect the clusters manually")
