---
apiVersion: ramendr.openshift.io/v1alpha1
kind: RamenConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  # leaderElect: true // enable during in cluster execution
  leaderElect: false
  resourceName: drorchestrator.ramendr.openshift.io
ramenControllerType: "drorchestrator"
