#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import json
import os
import sys
import time

from drenv import kubectl

POOL_NAME = "replicapool"
PVC_NAME = "rbd-pvc"


def rbd(*args, cluster=None):
    """
    Run a rbd command using the ceph toolbox on the specified cluster and
    return the output.
    """
    return kubectl.exec(
        "deploy/rook-ceph-tools",
        "--namespace=rook-ceph",
        "--",
        "rbd",
        *args,
        f"--pool={POOL_NAME}",
        context=cluster,
    )


def rbd_mirror_image_status(cluster, image):
    out = rbd(
        "mirror",
        "image",
        "status",
        image,
        "--format=json",
        cluster=cluster,
    )
    status = json.loads(out)

    # Exapand metrics json embdeded in the peer description.
    for peer in status["peer_sites"]:
        desc = peer.get("description", "")
        if ", " in desc:
            state, metrics = desc.split(", ", 1)
            peer["description"] = {
                "state": state,
                "metrics": json.loads(metrics),
            }

    return status


def test_volume_replication(primary, secondary):
    print(f"Deploying pvc {PVC_NAME} and vr vr-sample in cluster '{primary}'")
    kubectl.apply("--kustomize=test-data", context=primary)

    print(f"Waiting until pvc {PVC_NAME} is bound in cluster '{primary}'")
    kubectl.wait(
        f"pvc/{PVC_NAME}",
        "--for=jsonpath={.status.phase}=Bound",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=primary,
    )

    print(f"Waiting until vr vr-sample is completed in cluster '{primary}'")
    kubectl.wait(
        "volumereplication/vr-sample",
        "--for=condition=Completed",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=primary,
    )

    print(f"Waiting until vr vr-sample state is primary in cluster '{primary}'")
    kubectl.wait(
        "volumereplication/vr-sample",
        "--for=jsonpath={.status.state}=Primary",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=primary,
    )

    print(f"Looking up pvc {PVC_NAME} pv name in cluster '{primary}'")
    pv_name = kubectl.get(
        f"pvc/{PVC_NAME}",
        "--output=jsonpath={.spec.volumeName}",
        "--namespace=rook-ceph",
        context=primary,
    )

    print(f"Looking up rbd image for pv {pv_name} in cluster '{primary}'")
    rbd_image = kubectl.get(
        f"pv/{pv_name}",
        "--output=jsonpath={.spec.csi.volumeAttributes.imageName}",
        "--namespace=rook-ceph",
        context=primary,
    )

    print(f"rbd image {rbd_image} info in cluster '{primary}'")
    out = rbd("info", rbd_image, cluster=primary)
    print(out)

    print(f"Waiting until rbd image {rbd_image} is created in cluster '{secondary}'")
    for i in range(60):
        time.sleep(1)
        out = rbd("list", cluster=primary)
        if rbd_image in out:
            out = rbd("info", rbd_image, cluster=primary)
            print(out)
            break
    else:
        raise RuntimeError(f"Timeout waiting for image {rbd_image}")

    print(f"vr vr-sample info on primary cluster '{primary}'")
    kubectl.get(
        "volumereplication/vr-sample",
        "--output=yaml",
        "--namespace=rook-ceph",
        context=primary,
    )

    print(f"rbd mirror image status in cluster '{primary}'")
    image_status = rbd_mirror_image_status(primary, rbd_image)
    print(json.dumps(image_status, indent=2))

    print(f"Deleting pvc {PVC_NAME} and vr vr-sample in primary cluster '{primary}'")
    kubectl.delete("--kustomize=test-data", context=primary)

    print(f"Replication from cluster '{primary}' to cluster '{secondary}' succeeded")


if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} cluster1 cluster2")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster1 = sys.argv[1]
cluster2 = sys.argv[2]

test_volume_replication(cluster1, cluster2)
test_volume_replication(cluster2, cluster1)
