#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv.addons.rook import rbd_mirror

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} cluster1 cluster2")
    sys.exit(1)

cluster1 = sys.argv[1]
cluster2 = sys.argv[2]

rbd_mirror.test(cluster1, cluster2)
