#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv

# Update this when upgrading rook.
VERSION = "release-1.10"
BASE_URL = f"https://raw.githubusercontent.com/rook/rook/{VERSION}/deploy/examples"


def deploy(cluster):
    drenv.log_progress("Deploying rook ceph toolbox")
    drenv.kubectl_apply("--filename", f"{BASE_URL}/toolbox.yaml", profile=cluster)


def wait(cluster):
    drenv.log_progress("Waiting until rook-ceph-tools is rolled out")
    drenv.kubectl_rollout(
        "status",
        "deploy/rook-ceph-tools",
        "--namespace",
        "rook-ceph",
        "--timeout",
        "300s",
        profile=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
