#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv import kubectl

# Update this when upgrading rook.
VERSION = "release-1.10"
BASE_URL = f"https://raw.githubusercontent.com/rook/rook/{VERSION}/deploy/examples"


def deploy(cluster):
    print("Deploying rook ceph toolbox")
    kubectl.apply("--filename", f"{BASE_URL}/toolbox.yaml", context=cluster)


def wait(cluster):
    print("Waiting until rook-ceph-tools is rolled out")
    kubectl.rollout(
        "status",
        "deploy/rook-ceph-tools",
        "--namespace=rook-ceph",
        "--timeout=300s",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
