#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

# Use latest good commit and the matching image tag (found using quay.io).
VERSION = "629b9e066e342d7c0ce8141aa2f1f3ca5128c771"
IMAGE_TAG = f"2.4.0-{VERSION}"


BASE_URL = f"https://raw.githubusercontent.com/stolostron/multicloud-operators-foundation/{VERSION}/deploy/foundation/hub"


def deploy(cluster):
    print("Deploying ocm controller")
    with drenv.kustomization(
        "kustomization.yaml",
        base_url=BASE_URL,
        image_tag=IMAGE_TAG,
    ) as kustomization:
        kubectl.apply("--kustomize", kustomization, context=cluster)


def wait(cluster):
    print("Waiting for ocm controller rollout")
    kubectl.rollout(
        "status",
        "deploy/ocm-controller",
        namespace="open-cluster-management",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
