#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
from drenv import cache

os.chdir(os.path.dirname(__file__))
cache.refresh("operator", "addons/kubevirt-operator-1.5.2.yaml")
cache.refresh("cr", "addons/kubevirt-cr-1.5.2.yaml")
