#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os

from drenv import cache

os.chdir(os.path.dirname(__file__))

path = cache.path("addons/kubevirt-operator-1.2.1.yaml")
cache.fetch("operator", path)

path = cache.path("addons/kubevirt-cr-1.2.1.yaml")
cache.fetch("cr", path)
