#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os

from drenv import cache

os.chdir(os.path.dirname(__file__))
path = cache.path("addons/olm-crds-0.27.yaml")
cache.fetch("crds", path)

path = cache.path("addons/olm-operators-0.27.yaml")
cache.fetch("operators", path)
