#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

import drenv
from drenv import kubectl

VERSION = "v0.22.0"
BASE_URL = f"https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{VERSION}"
NAMESPACE = "olm"


def deploy(cluster):
    print("Deploying olm crds")

    # Using Server-side Apply to avoid this failure:
    #   The CustomResourceDefinition "clusterserviceversions.operators.coreos.com"
    #   is invalid: metadata.annotations: Too long: must have at most 262144 bytes
    # See https://medium.com/pareture/kubectl-install-crd-failed-annotations-too-long-2ebc91b40c7d
    kubectl.apply(
        f"--filename={BASE_URL}/crds.yaml",
        "--server-side=true",
        context=cluster,
    )

    print("Waiting until cdrs are established")
    kubectl.wait(
        filename=f"{BASE_URL}/crds.yaml",
        condition="condition=established",
        context=cluster,
    )

    print("Deploying olm")
    kubectl.apply("--filename", f"{BASE_URL}/olm.yaml", context=cluster)


def wait(cluster):
    for operator in "olm-operator", "catalog-operator":
        print(f"Waiting until {operator} is rolled out")
        kubectl.rollout(
            "status",
            "deploy",
            operator,
            f"--namespace={NAMESPACE}",
            context=cluster,
        )

    print("Waiting until olm packageserver succeeds")
    drenv.wait_for(
        "csv/packageserver",
        output="jsonpath={.status.phase}",
        namespace=NAMESPACE,
        profile=cluster,
    )
    kubectl.wait(
        resource="csv/packageserver",
        condition="jsonpath={.status.phase}=Succeeded",
        namespace=NAMESPACE,
        context=cluster,
    )

    print("Waiting for olm pakcage server rollout")
    kubectl.rollout(
        "status",
        "deploy/packageserver",
        f"--namespace={NAMESPACE}",
        context=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
