# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloud-credentials
  namespace: $namespace
data:
  cloud: $cloud
