# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    cluster.open-cluster-management.io/backup: resource
  name: $name
  namespace: $namespace
data:
  ramen_manager_config.yaml: |
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: RamenConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:9289
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: hub.ramendr.openshift.io
    ramenControllerType: dr-hub
    maxConcurrentReconciles: 50
    drClusterOperator:
      deploymentAutomationEnabled: $auto_deploy
      s3SecretDistributionEnabled: true
      channelName: alpha
      packageName: ramen-dr-cluster-operator
      namespaceName: ramen-system
      catalogSourceName: ramen-catalog
      catalogSourceNamespaceName: ramen-system
      clusterServiceVersionName: ramen-dr-cluster-operator.v0.0.1
    kubeObjectProtection:
      veleroNamespaceName: velero
    s3StoreProfiles:
    - s3ProfileName: minio-on-$cluster1
      s3Bucket: bucket
      s3CompatibleEndpoint: $minio_url_cluster1
      s3Region: us-west-1
      s3SecretRef:
        name: ramen-s3-secret-$cluster1
        namespace: ramen-system
      veleroNamespaceSecretKeyRef:
        key: cloud
        name: cloud-credentials
    - s3ProfileName: minio-on-$cluster2
      s3Bucket: bucket
      s3CompatibleEndpoint: $minio_url_cluster2
      s3Region: us-east-1
      s3SecretRef:
        name: ramen-s3-secret-$cluster2
        namespace: ramen-system
      veleroNamespaceSecretKeyRef:
        key: cloud
        name: cloud-credentials
