apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.openshift.io/infrastructure-features: '["disconnected"]'
  name: ramen-dr-cluster-operator.v0.0.0
  namespace: placeholder
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VolumeReplicationGroup is the Schema for the volumereplicationgroups
        API
      displayName: Volume Replication Group
      kind: VolumeReplicationGroup
      name: volumereplicationgroups.ramendr.openshift.io
      version: v1alpha1
  description: Ramen is a disaster-recovery orchestrator for stateful applications
    across a set of peer kubernetes clusters which are deployed and managed using
    open-cluster-management (OCM) and provides cloud-native interfaces to orchestrate
    the life-cycle of an application's state on PersistentVolumes.
  displayName: Ramen DR Cluster Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Storage
  - Integration & Delivery
  - OpenShift Optional
  links:
  - name: Ramen
    url: https://github.com/RamenDR/ramen
  maintainers:
  - email: bmekhiss@redhat.com
    name: Benamar Mekhissi
  - email: srangana@redhat.com
    name: Shyam Ranganathan
  - email: vdeenadh@redhat.com
    name: Veera Deenadhayalan
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.0.0
