#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

import drenv
from drenv import kubectl

VERSION = "v0.22.0"
BASE_URL = f"https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{VERSION}"
NAMESPACE = "olm"


def deploy(cluster):
    drenv.log_progress("Deploying olm crds")

    # Using Server-side Apply to avoid this failure:
    #   The CustomResourceDefinition "clusterserviceversions.operators.coreos.com"
    #   is invalid: metadata.annotations: Too long: must have at most 262144 bytes
    # See https://medium.com/pareture/kubectl-install-crd-failed-annotations-too-long-2ebc91b40c7d
    kubectl.apply(
        "--filename",
        f"{BASE_URL}/crds.yaml",
        "--server-side=true",
        profile=cluster,
    )

    drenv.log_progress("Waiting until cdrs are established")
    kubectl.wait(
        "--for",
        "condition=established",
        "--filename",
        f"{BASE_URL}/crds.yaml",
        profile=cluster,
    )

    drenv.log_progress("Deploying olm")
    kubectl.apply("--filename", f"{BASE_URL}/olm.yaml", profile=cluster)


def wait(cluster):
    for operator in "olm-operator", "catalog-operator":
        drenv.log_progress(f"Waiting until {operator} is rolled out")
        kubectl.rollout(
            "status",
            "deploy",
            operator,
            "--namespace",
            NAMESPACE,
            profile=cluster,
        )

    drenv.log_progress("Waiting until olm packageserver succeeds")
    drenv.wait_for(
        "csv/packageserver",
        output="jsonpath={.status.phase}",
        namespace=NAMESPACE,
        profile=cluster,
    )
    kubectl.wait(
        "csv/packageserver",
        "--namespace",
        NAMESPACE,
        "--for",
        "jsonpath={.status.phase}=Succeeded",
        "--timeout",
        "300s",
        profile=cluster,
    )

    drenv.log_progress("Waiting for olm pakcage server rollout")
    kubectl.rollout(
        "status",
        "deploy/packageserver",
        "--namespace",
        NAMESPACE,
        profile=cluster,
    )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
