#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv import kubectl

CRDS = [
    "../hack/test/volsync.backube_replicationsources.yaml",
    "../hack/test/volsync.backube_replicationdestinations.yaml",
]


def deploy(cluster):
    print("Deploying volsync crds")
    for crd in CRDS:
        kubectl.apply(f"--filename={crd}", context=cluster)


def wait(cluster):
    print("Waiting until cdrs are established")
    for crd in CRDS:
        kubectl.wait(
            "--for=condition=established",
            f"--filename={crd}",
            context=cluster,
        )


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
