# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# yamllint disable rule:line-length
---
name: e2e daily

on:
  # Run every day on 03:00.
  schedule:
    - cron: '0 3 * * *'
  # Allow manual run.
  # (Actions -> E2E Daily -> Run workflow)
  workflow_dispatch:

jobs:
  refresh-cache:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - e2e-rdr-2
          - e2e-rdr-3
    runs-on: ${{ matrix.runner }}
    if: github.repository == 'RamenDR/ramen'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create virtual environment
        run: hack/make-venv .venv

      - name: Refresh cache
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          retry_wait_seconds: 60
          max_attempts: 10
          command: |
            cd test
            source ../venv
            drenv cache envs/regional-dr.yaml

  prune-images:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - e2e-rdr-2
          - e2e-rdr-3
    runs-on: ${{ matrix.runner }}
    if: github.repository == 'RamenDR/ramen'
    steps:
      - name: Prune images
        run: podman image prune -f
