---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ramen-hub-subscription
  namespace: ramen-system
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: ramen-hub
  source: ramen-catalog
  sourceNamespace: ramen-system
  startingCSV: ramen-hub.v0.0.1
